name: On Release

permissions:
  id-token: write
  contents: read
  actions: write #Need for deleting artifact

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy-sam-app:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'changeset-release/')
    name: Deploy SAM to prod
    uses: ./.github/workflows/deploy-sam-app.yml

  deploy-netlify-app:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'changeset-release/')
    name: Deploy Netlify APP to prod
    uses: ./.github/workflows/deploy-to-netlify.yml
    secrets: inherit

  send-changelog-to-discord:
    runs-on: ubuntu-latest
    needs: [deploy-sam-app, deploy-netlify-app]
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install Dependencies
        run: |
          pnpm c set recursive-install=false --location=project
          pnpm install --no-frozen-lockfile

      - name: Build Changelog-formatter
        run: |
          pnpm --filter "./tools/changelog-formatter" install --no-frozen-lockfile
          pnpm --filter @cloudifybiz/changelog-formatter run build

      - name: Send to Discord
        run: |
          cd ./tools/changelog-formatter 
          pnpm send-to-discord
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
          DISCORD_RELEASE_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
